### ISSUE TITLE
Update app on f-droid

### ISSUE THREAD

**Issue by daycode** [ojacquemart/vlilleChecker#106]
The app on f-droid is version 3.1.1, could you update it ?

**Comment by ojacquemart** [comment]
Thanks for the report. :+1: 

I will investigate on it

**Comment by ojacquemart** [comment]
The metadata seems up-to-date: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.vlille.checker.txt

I just pushed a 4.2.2. Will see if it brings the new version to fdroid.

**Comment by daycode** [comment]
Thank you for you app, if you need some help with the develoment, feel free to call me, I'm on Lille too (et français aussi 😄 )

**Comment by daycode** [comment]
I just saw that [page](https://f-droid.org/wiki/page/com.vlille.checker). Hope it'll help you anderstand why there wasn't updates on f-droid.

**Comment by ojacquemart** [comment]
Yep, it seems that since the 3.1.1, the app was not compiling.
It should be fixed in the 4.2.2.

It could be interesting to use a service like travis or circle to has a build status. Will you be interested to contribute?

**Comment by ojacquemart** [comment]
Il faut attendre la mise à jour de leur base pour voir si la 4.2.2 compile chez eux ;)

**Comment by ojacquemart** [comment]
The badge is a good idea :) I "plussoie" 👍

**Comment by ojacquemart** [comment]
I finally get a travis build working: https://travis-ci.org/ojacquemart/vlilleChecker/builds/224496578

See https://github.com/ojacquemart/vlilleChecker/commit/2bcb203ef50eba8525d50c87af0f8622166fb35f

I pushed a 4.2.2 without bumping the androidManifest version* attributes.
Seems like fdroid did not catch the new version. I will wait till monday and I will open a issue in the fdroid repo to get some help.

**Comment by ojacquemart** [comment]
I did some changes thanks to fdroid help: https://gitlab.com/fdroid/fdroiddata/issues/717

I still need to test the app on various versions and also check with the fdroid tool mentionned in the issue :+1:

**Comment by daycode** [comment]
Thanks for all the work 😘

**Comment by ojacquemart** [comment]
Finally, a new version is availavable on fdroid: 
https://f-droid.org/repository/browse/?fdid=com.vlille.checker

Thanks again @daycode for the report :+1:
