### ISSUE TITLE
Track app usage

### ISSUE THREAD

**Issue by ojacquemart** [ojacquemart/vlilleChecker#128]
Have some statistics about the app usages.

**Comment by paynemiller92** [comment]
I'll pick this one up.

**Comment by paynemiller92** [comment]
I want to use [Google Analytics](https://developers.google.com/analytics/devguides/collection/android/v4/) as the platform for capturing analytics. Do you have an account I can use? I imagine you would like to own the account that houses all this.

**Comment by ojacquemart** [comment]
Thanks for your interest 👍 

Here is a dev tracking ID I just generated if you would like to use Google Analytics: UA-127812758-1

Is Google Analytics better than Firebase? Or is it for a different purpose?

**Comment by ojacquemart** [comment]
What I would like to have is pretty simple:

- Click on Stars tab, List tab, Maps tab
- Click on location button in the maps view
- Click on settings
- Click on about
- Click on stars
- Number of favorite stations (if possible)

Add anything you want if you think, it could be useful 😄

**Comment by paynemiller92** [comment]
@ojacquemart [Pull Request ](https://github.com/ojacquemart/vlilleChecker/pull/133) submitted! Thanks for letting me work on this. Cheers from the USA! 🇺🇸 🇫🇷

**Comment by ojacquemart** [comment]
Closed via https://github.com/ojacquemart/vlilleChecker/commit/91795e813230692371db65b11c1af8bdedfe250d
