### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by datalossdetector** [ojacquemart/vlilleChecker#139]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, the star assigned is lost in StationInfoActivity
![2019-07-21 05-46-28_before](https://user-images.githubusercontent.com/53469180/62286201-8818ec80-b457-11e9-8063-5cd832b53e8d.png)
![2019-07-21 05-46-28_after](https://user-images.githubusercontent.com/53469180/62286202-88b18300-b457-11e9-8749-aa9dc84cc2e4.png)

2) When I change the orientation of the device screen, Update Time ToggleButton changes its color in SettingsActivity
![2019-07-21 03-44-22_before](https://user-images.githubusercontent.com/53469180/62286064-4425e780-b457-11e9-9c17-5d9d1d51600f.png)
![2019-07-21 03-44-22_after](https://user-images.githubusercontent.com/53469180/62286065-44be7e00-b457-11e9-828f-17a9ff63555b.png)

3) When I change the orientation of the device screen, the link to the email loses the highlight in AboutActivity
![2019-07-21 10-49-27_before](https://user-images.githubusercontent.com/53469180/62285865-c8c43600-b456-11e9-9df6-ee7d1887daee.png)
![2019-07-21 10-49-27_after](https://user-images.githubusercontent.com/53469180/62285866-c8c43600-b456-11e9-98b3-c36eb1351f3e.png)

**Comment by ojacquemart** [comment]
Thanks for your feedback!
Indeed, it's a bug... I will take a look :)

**Comment by ojacquemart** [comment]
@dlicse1  It should be fixed. I will do a release soon.

Thanks again for your report!
