### ISSUE TITLE
Dialog Disappears on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [ojacquemart/vlilleChecker#97]
When I perform these sequences of events, the dialog on screen disappears:

Sequence 1: 
1. Click on More...
2. Click on Settings
3. Click on Stations Around Me
4. Orientation Change

**Comment by ojacquemart** [comment]
Android creates a new view when switching orientation. It is intended.
It's not really a top priority. 

I am closing. You should provide a PR, I could consider it :)

**Comment by ojacquemart** [comment]
Android creates a new view when switching orientation. It is intended.
It's not really a top priority. 

I am closing. You should provide a PR, I could consider it :)
